sudo: required
services:
  - docker

before_install:
  - docker build -t loboda/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true loboda/react-test npm test

after_success:
  - docker build -t loboda/multi-client ./client
  - docker build -t loboda/multi-nginx ./nginx
  - docker build -t loboda/multi-server ./server
  - docker build -t loboda/multi-worker ./worker
#log to docker CLI
  - echo "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
#take the images to push thm to docker hub
  - docker push loboda/multi-client
  - docker push loboda/multi-nginx
  - docker push loboda/multi-server
  - docker push loboda/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-989786114304'
#   bucket_path: 'docker-multi'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY